### ISSUE TITLE
您好，这个代码如何使用？

### ISSUE THREAD

**Issue by feng99** [gaoc1990/php_3pc#1]
大致看了下，代码里还用到了swoole，
如果是php-fpm的能直接使用吗？

**Comment by gaoc1990** [comment]
swoole用来做事务管理器的。  需要启动事务管理器，代码只是demo， 想用做产品还需要很多完善的地方

**Comment by feng99** [comment]
Demo2和demo3看起来是一样的，区别在哪里？


哦，那就是必须安装swoole才可以用了。

**Comment by feng99** [comment]
想用到生产环境中，还有哪些需要完善的？


事务管理器，必须用swoole实现吗？
